use_frameworks!

platform :ios, '9.0'

target 'VideoPlayerLib_Example' do
  pod 'VideoPlayerLib', :path => '../'

  target 'VideoPlayerLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
